version: "3.8"
networks:
  docker_xuecheng:
    external: true

services:
  nginx-static:
    container_name: nginx-static
    image: nginx:latest
    volumes:
      - ./nginx-static/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-static/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-static/dist:/usr/share/nginx/dist
    ports:
      - "80:80"
    networks:
      docker_xuecheng:
        ipv4_address: 172.20.20.1

  # nginx-portal:
  #   container_name: nginx-portal
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx-portal/conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx-portal/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx-portal/dist:/usr/share/nginx/dist
  #   ports:
  #     - "8601:8601"
  #   networks:
  #     docker_xuecheng:
  #       ipv4_address: 172.20.20.2

  nginx-portal-serve:
    container_name: nginx-portal-serve
    image: node:16.17.0-slim
    volumes:
      - ./nginx-portal-serve/project-xczx2-portal-vue-ts:/root/project-xczx2-portal-vue-ts
    ports:
      - "8601:8601"
    tty: true
    command: cd /root/project-xczx2-portal-vue-ts && npm run serve
    networks:
      docker_xuecheng:
        ipv4_address: 172.20.20.2